<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { useRouter } from 'vue-router'; import { ArrowRight, Box, CircleCheck, Clock, FirstAidKit } from '@element-plus/icons-vue'; import { deviceApi, diagnosticApi, userFacingApiError } from '../api'; import type { Device,Diagnostic } from '../types'; import { useAuthStore } from '../stores'
const auth=useAuthStore();const router=useRouter();const devices=ref<Device[]>([]);const records=ref<Diagnostic[]>([]);const loading=ref(true);const loadError=ref('')
// 此前只有 try/finally：接口挂了也照样渲染「0 已绑定设备 / 0 累计诊断」，
// 用户会以为数据被清空了。加载失败必须说是失败，不能把 0 当事实。
onMounted(async()=>{try{[devices.value,records.value]=await Promise.all([deviceApi.list(),diagnosticApi.list()])}catch(e){loadError.value=userFacingApiError(e,'工作台数据加载失败，请稍后重试')}finally{loading.value=false}})
const statusLabel=(s:string)=>({resolved:'已解决',report_ready:'报告已生成',unresolved:'未解决',in_progress:'进行中',collecting:'待开始'}[s]||s)
</script>
<template><div class="page" v-loading="loading"><section class="hero"><div><p class="eyebrow">ROBOTCARE WORKSPACE</p><h1>{{ auth.user?.name || auth.user?.full_name || '你好' }}，今天设备还好吗？</h1><p>从使用指导到分步排障，所有操作都基于安全边界与可追溯资料。</p><div class="hero-actions"><el-button class="brand-button" type="primary" size="large" :icon="FirstAidKit" @click="router.push('/diagnostics/new')">开始故障排查</el-button><el-button size="large" :icon="Box" @click="router.push('/devices')">管理我的设备</el-button></div></div><div class="robot-orbit"><span class="pulse"></span><div class="robot">⌂<small>AI</small></div><div class="orbit-label"><span class="status-dot"></span>服务正常</div></div></section><el-alert v-if="loadError" class="load-error" :title="loadError" type="error" :closable="false" show-icon/><section class="stats"><div class="panel"><el-icon><Box/></el-icon><span><b>{{loadError?'--':devices.length}}</b><small>已绑定设备</small></span></div><div class="panel"><el-icon><FirstAidKit/></el-icon><span><b>{{loadError?'--':records.length}}</b><small>累计诊断</small></span></div><div class="panel"><el-icon><CircleCheck/></el-icon><span><b>{{loadError?'--':records.filter(x=>x.resolved||x.status==='resolved').length}}</b><small>已成功解决</small></span></div></section><div class="content-grid"><section class="panel recent"><div class="section-head"><div><h2>最近诊断</h2><p>继续上次流程或查看处理结果</p></div><router-link to="/history">查看全部 <el-icon><ArrowRight/></el-icon></router-link></div><div v-if="records.length" class="record-list"><button v-for="r in records.slice(0,4)" :key="r.id" @click="router.push(`/diagnostics/${r.id}`)"><span class="record-icon"><Clock/></span><span><b>{{r.issue_description}}</b><small>{{r.device?.nickname||'扫地机器人'}} · {{r.created_at?.slice(0,10)||'最近'}}</small></span><el-tag :type="r.status==='resolved'?'success':r.status==='in_progress'?'warning':'info'" effect="light">{{statusLabel(r.status)}}</el-tag></button></div><div v-else class="empty">{{loadError?'诊断记录暂时读取不到，请稍后重试。':'暂无诊断记录，从一次安全排查开始吧。'}}</div></section><aside class="panel guide"><span>使用指南</span><h2>先别急着报修</h2><p>主刷缠绕、传感器积灰和网络变化，是常见且可安全处理的问题。</p><router-link to="/guides">检索对应型号资料 →</router-link></aside></div></div></template>
<style scoped>.load-error{margin-bottom:14px}.hero{min-height:250px;border-radius:20px;background:linear-gradient(115deg,#f0faf6,#dff4eb);border:1px solid #cee9dd;padding:40px 50px;display:flex;justify-content:space-between;align-items:center;overflow:hidden}.hero h1{font-size:32px;margin:10px 0}.hero p:not(.eyebrow){color:#566b62}.hero-actions{margin-top:28px}.robot-orbit{width:230px;height:180px;position:relative;display:grid;place-items:center}.pulse{position:absolute;width:160px;height:160px;border-radius:50%;border:1px solid #a7dbc8;box-shadow:0 0 0 28px rgba(8,127,91,.04),0 0 0 55px rgba(8,127,91,.025)}.robot{position:relative;width:105px;height:105px;border-radius:50%;background:#fff;border:5px solid #164b3b;box-shadow:0 15px 30px rgba(20,77,59,.17);display:grid;place-items:center;color:#164b3b;font-size:36px;font-weight:800}.robot small{position:absolute;font-size:9px;bottom:18px}.orbit-label{position:absolute;bottom:1px;background:white;padding:8px 14px;border-radius:20px;box-shadow:0 6px 18px rgba(20,77,59,.12);font-size:12px}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:18px 0}.stats>div{padding:20px 24px;display:flex;align-items:center;gap:16px}.stats .el-icon{font-size:23px;color:var(--brand);background:var(--soft);padding:12px;border-radius:12px;box-sizing:content-box}.stats b,.stats small{display:block}.stats b{font-size:24px}.stats small{color:var(--muted);margin-top:3px}.content-grid{display:grid;grid-template-columns:1fr 310px;gap:18px}.recent{padding:26px}.section-head{display:flex;justify-content:space-between;align-items:center}.section-head h2{margin:0;font-size:19px}.section-head p{color:var(--muted);font-size:12px;margin:5px 0}.section-head a{color:var(--brand);font-size:13px;display:flex;align-items:center;gap:5px}.record-list{margin-top:14px}.record-list button{width:100%;border:0;border-top:1px solid var(--line);padding:15px 5px;background:white;display:grid;grid-template-columns:40px 1fr auto;align-items:center;gap:12px;text-align:left;cursor:pointer}.record-list button:hover b{color:var(--brand)}.record-icon{width:36px;height:36px;border-radius:10px;background:#f1f5f3;display:grid;place-items:center;color:#60736b}.record-list b,.record-list small{display:block}.record-list b{font-size:13px;max-width:520px;white-space:nowrap;text-overflow:ellipsis;overflow:hidden}.record-list small{font-size:11px;color:var(--muted);margin-top:5px}.guide{padding:28px;background:#123b30;color:white;border:0}.guide>span{font-size:11px;color:#77d3b2;letter-spacing:1px}.guide h2{margin:22px 0 12px}.guide p{font-size:13px;line-height:1.8;color:#c7dcd5}.guide a{display:block;margin-top:35px;color:#79dbb8;font-size:13px;font-weight:700}
/* 工作台此前没有任何断点：hero 左右分栏 + stats 三列 + 内容区 1fr/310px
   在 390px 屏上整体溢出 74px（2026-08-05 实测）。 */
@media(max-width:900px){
  .hero{flex-direction:column;align-items:flex-start;min-height:0;padding:26px 20px;border-radius:16px}
  .hero h1{font-size:24px;line-height:1.35}
  .hero p:not(.eyebrow){font-size:14px;line-height:1.7}
  .robot-orbit{display:none}
  .hero-actions{margin-top:20px;display:flex;flex-wrap:wrap;gap:10px;width:100%}
  .hero-actions .el-button{margin-left:0;flex:1 1 auto}
  .stats{grid-template-columns:minmax(0,1fr);gap:12px;margin:14px 0}
  .stats>div{padding:16px 18px}
  .content-grid{grid-template-columns:minmax(0,1fr)}
  .recent{padding:20px}
  .record-list b{max-width:none}
  .record-list button{grid-template-columns:36px minmax(0,1fr);grid-template-areas:'icon text' '. tag';row-gap:8px;padding:14px 2px}
  .record-icon{grid-area:icon}
  .record-list button>span:nth-child(2){grid-area:text}
  .record-list .el-tag{grid-area:tag;justify-self:start}
  .guide{padding:22px}
  .guide a{margin-top:22px}
}</style>
