<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'; import { Plus,Box,MoreFilled } from '@element-plus/icons-vue'; import { apiError,deviceApi,modelApi } from '../api'; import type { Device,RobotModel } from '../types'; import { useIsNarrow } from '../viewport'
const isNarrow=useIsNarrow()
const devices=ref<Device[]>([]),models=ref<RobotModel[]>([]),loading=ref(true),saving=ref(false),dialog=ref(false);const form=reactive({robot_model_id:'' as string|number,nickname:'',serial_number:''})
async function load(){loading.value=true;try{[devices.value,models.value]=await Promise.all([deviceApi.list(),modelApi.list()])}catch(e){ElMessage.error(apiError(e))}finally{loading.value=false}}
async function save(){if(!form.robot_model_id||!form.nickname.trim())return ElMessage.warning('请选择型号并填写设备名称');saving.value=true;try{await deviceApi.create({robot_model_id:form.robot_model_id,nickname:form.nickname.trim(),serial_number:form.serial_number.trim()||undefined});dialog.value=false;Object.assign(form,{robot_model_id:'',nickname:'',serial_number:''});ElMessage.success('设备添加成功');await load()}catch(e){ElMessage.error(apiError(e,'设备添加失败'))}finally{saving.value=false}}
async function remove(d:Device){try{await ElMessageBox.confirm(`确认删除“${d.nickname}”？有诊断历史的设备将无法删除。`,'删除设备',{type:'warning'});await deviceApi.remove(d.id);ElMessage.success('已删除');await load()}catch(e){if(e!=='cancel')ElMessage.error(apiError(e,'删除失败'))}}
onMounted(load)
</script>
<template><div class="page"><div class="page-head"><div><h1>我的设备</h1><p>绑定你正在使用的扫地机器人，诊断时系统会严格匹配对应型号资料。</p></div><el-button class="brand-button" type="primary" :icon="Plus" @click="dialog=true">添加设备</el-button></div><div v-loading="loading" class="device-grid"><article v-for="d in devices" :key="d.id" class="panel device-card"><div class="card-top"><span class="device-icon"><el-icon><Box/></el-icon></span><el-dropdown trigger="click"><el-button text circle :icon="MoreFilled"/><template #dropdown><el-dropdown-menu><el-dropdown-item @click="remove(d)">删除设备</el-dropdown-item></el-dropdown-menu></template></el-dropdown></div><p class="model">{{d.robot_model?.brand||'Haier'}} · {{d.robot_model?.code}}</p><h2>{{d.nickname}}</h2><p class="model-name">{{d.robot_model?.name}}</p><div class="meta"><span>序列号</span><b>{{d.serial_number||'未填写'}}</b></div><router-link :to="`/diagnostics/new?device=${d.id}`">为此设备开始诊断 →</router-link></article><button class="add-card" @click="dialog=true"><el-icon><Plus/></el-icon><b>添加另一台设备</b><span>支持 JH69U1、VC35U1 等已配置型号</span></button></div><div v-if="!loading&&!devices.length" class="panel empty"><el-icon size="44"><Box/></el-icon><h3>还没有绑定设备</h3><p>添加设备后，才能开始型号级使用指导和故障排查。</p><el-button class="brand-button" type="primary" @click="dialog=true">添加第一台设备</el-button></div><el-dialog v-model="dialog" title="添加扫地机器人" :width="isNarrow?'92vw':'480px'"><el-form label-position="top"><el-form-item label="型号" required><el-select v-model="form.robot_model_id" placeholder="选择设备型号" style="width:100%"><el-option v-for="m in models" :key="m.id" :label="`${m.code} · ${m.name}`" :value="m.id"/></el-select></el-form-item><el-form-item label="设备名称" required><el-input v-model="form.nickname" placeholder="例如：客厅扫地机器人" maxlength="100"/></el-form-item><el-form-item label="序列号（选填）"><el-input v-model="form.serial_number" placeholder="可在设备铭牌上查看"/></el-form-item><el-alert title="请按设备铭牌手动选择型号，错误型号可能导致排查步骤不适用。" type="warning" :closable="false" show-icon/></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button class="brand-button" type="primary" :loading="saving" @click="save">确认添加</el-button></template></el-dialog></div></template>
<style scoped>/* 原为 repeat(3,minmax(260px,1fr))：3 列各自最小 260px + 2 个 18px 间距 = 816px 硬地板，
   390px 手机上整页横向溢出 162px（实测）。改 minmax(0,1fr) 去掉地板 + 逐级降列，
   宽屏仍是 3 列（视觉不变），窄屏才降。不用 auto-fill 是因为它在 1440px 下会自己变 4 列。 */
.device-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.device-card,.add-card{min-height:285px;padding:25px}.card-top{display:flex;justify-content:space-between}.device-icon{width:52px;height:52px;border-radius:15px;background:var(--soft);display:grid;place-items:center;color:var(--brand);font-size:24px}.model{font-size:11px;color:var(--brand);font-weight:750;letter-spacing:.6px;margin:24px 0 8px}.device-card h2{font-size:21px;margin:0 0 7px}.model-name{color:var(--muted);font-size:13px;height:18px}.meta{border-top:1px solid var(--line);margin-top:20px;padding-top:14px;display:flex;justify-content:space-between;font-size:12px}.meta span{color:var(--muted)}.device-card>a{display:block;color:var(--brand);font-size:13px;font-weight:700;margin-top:22px}.add-card{border:1.5px dashed #bad3c9;border-radius:16px;background:transparent;color:var(--muted);display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;cursor:pointer}.add-card:hover{border-color:var(--brand);background:#f4fbf8}.add-card .el-icon{font-size:28px;color:var(--brand)}.add-card span{font-size:11px}.empty h3{color:var(--ink)}
@media(max-width:900px){.device-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:640px){.device-grid{grid-template-columns:minmax(0,1fr);gap:14px}.device-card,.add-card{min-height:auto;padding:20px}.add-card{min-height:130px}.device-card h2{font-size:19px}}</style>
