<script setup lang="ts">import { onMounted,ref } from 'vue';import { useRoute } from 'vue-router';import { CopyDocument,Download,Printer } from '@element-plus/icons-vue';import { diagnosticApi,userFacingApiError } from '../api';import type { ServiceReport } from '../types';const route=useRoute(),report=ref<ServiceReport|null>(null),loading=ref(true),pdfLoading=ref(false),loadError=ref(''),pdfError=ref('');onMounted(async()=>{try{report.value=await diagnosticApi.report(String(route.params.id))}catch(e){loadError.value=userFacingApiError(e,'报告尚未生成或暂时无法读取')}finally{loading.value=false}});async function copy(){if(!report.value)return;/* navigator.clipboard 在非 HTTPS、iOS 权限拒绝、旧内核下会抛或不存在。
 此前没有 catch：用户点了复制什么都没发生，也不知道为什么，报告又是要交给售后的关键材料。
 降级到 execCommand，再不行就明确告诉用户"请手动选中复制"。 */
try{if(!navigator.clipboard?.writeText)throw new Error('clipboard unavailable');await navigator.clipboard.writeText(report.value.content);ElMessage.success('报告内容已复制');return}catch{}
try{const area=document.createElement('textarea');area.value=report.value.content;area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();const ok=document.execCommand?.('copy');area.remove();if(ok){ElMessage.success('报告内容已复制');return}}catch{}
ElMessage.warning('当前浏览器不允许自动复制，请长按或选中下方报告内容手动复制')}function printReport(){globalThis.print()}async function downloadPdf(){if(!report.value)return;pdfLoading.value=true;pdfError.value='';let stage='生成';try{const meta=await diagnosticApi.createPdfReport(String(route.params.id));stage='下载';const blob=await diagnosticApi.downloadPdfReport(String(route.params.id));const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=meta.filename;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);ElMessage.success('PDF 售后报告已下载')}catch(e){pdfError.value=userFacingApiError(e,`PDF ${stage}失败，请稍后重试`)}finally{pdfLoading.value=false}}</script>
<template><div class="page report-page" v-loading="loading"><div class="page-head"><div><p class="eyebrow">SERVICE HANDOFF</p><h1>售后诊断报告</h1><p>将已完成的安全排查过程整理为可交付的文字材料。</p></div><div v-if="report"><el-button :icon="CopyDocument" @click="copy">复制内容</el-button><el-button :icon="Printer" @click="printReport">浏览器打印</el-button><el-button class="brand-button" type="primary" :icon="Download" :loading="pdfLoading" @click="downloadPdf">下载正式 PDF</el-button></div></div><el-alert v-if="loadError" :title="loadError" type="error" :closable="false" show-icon/><el-alert v-if="pdfError" :title="pdfError" type="error" :closable="false" show-icon/><article v-if="report" class="paper"><header><div class="paper-brand"><span>R</span><div><b>RobotCare AI</b><small>第三方安全排障助手</small></div></div><div class="number"><small>报告编号</small><b>{{report.report_number}}</b></div></header><div class="report-meta"><span><small>诊断会话</small>#{{report.session_id}}</span><span><small>生成时间</small>{{report.created_at?.replace('T',' ').slice(0,19)}}</span><span><small>报告状态</small>已生成</span></div><pre>{{report.content}}</pre><footer><b>重要声明</b><p>本报告由独立第三方辅助工具根据用户反馈自动整理，不代表海尔官方诊断结论。涉及拆机、电池、电路、冒烟、异味、漏液或异常高温时，请停止操作并联系官方售后。</p></footer></article><div v-else-if="!loading" class="panel empty">没有找到该诊断报告，请先完成全部安全排查步骤。</div></div></template>
<style scoped>.report-page{max-width:1100px}.paper{background:white;border:1px solid var(--line);box-shadow:0 12px 40px rgba(31,57,48,.08);padding:45px 55px;margin-bottom:50px}.paper header{display:flex;justify-content:space-between;align-items:center;padding-bottom:27px;border-bottom:2px solid #183e32}.paper-brand{display:flex;gap:11px;align-items:center}.paper-brand>span{width:40px;height:40px;border-radius:10px;background:var(--brand);color:#fff;display:grid;place-items:center;font-size:20px;font-weight:800}.paper-brand b,.paper-brand small,.number b,.number small{display:block}.paper-brand small,.number small{color:var(--muted);font-size:10px;margin-bottom:5px}.number{text-align:right}.report-meta{display:grid;grid-template-columns:repeat(3,1fr);background:#f4f8f6;padding:18px 22px;margin:25px 0}.report-meta span{font-size:13px}.report-meta small{display:block;color:var(--muted);font-size:10px;margin-bottom:5px}.paper pre{font:14px/2 "Microsoft YaHei",sans-serif;white-space:pre-wrap;min-height:320px;color:#263a33}.paper footer{border-top:1px solid var(--line);padding-top:22px;color:#7b5a2e}.paper footer b{font-size:12px}.paper footer p{font-size:11px;line-height:1.8}.window{display:none}
/* 报告页此前没有任何断点：paper 左右内边距 55px + report-meta 固定三列，
   390px 屏上正文被挤成窄条、meta 三列互相压字（2026-08-06 体检）。 */
@media(max-width:640px){
  .paper{padding:24px 18px;margin-bottom:28px}
  .paper header{flex-direction:column;align-items:flex-start;gap:14px;padding-bottom:18px}
  .number{text-align:left}
  .report-meta{grid-template-columns:minmax(0,1fr);gap:12px;padding:14px 16px;margin:18px 0}
  .paper pre{font-size:13px;line-height:1.9;min-height:auto}
  .page-head>div:last-child{display:flex;flex-wrap:wrap;gap:8px;width:100%}
  .page-head .el-button{margin-left:0;flex:1 1 auto}
}
@media print{.report-page>.page-head{display:none}.report-page{padding:0}.paper{box-shadow:none;border:0;margin:0}.paper footer{break-inside:avoid}}</style>
